export const ADD_ASSET_REQUEST = "ADD_ASSET_REQUEST";
export const ADD_ASSET_SUCCESS = "ADD_ASSET_SUCCESS";
export const ADD_ASSET_FAIL = "ADD_ASSET_FAIL";
export const DELETE_ASSET = "DELETE_ASSET";
